# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-06 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(max_length=500)),
                ('note_time', models.DateTimeField(verbose_name='data published')),
                ('note_body', models.TextField()),
                ('note_slug', models.SlugField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
